In [10]:
import cv2
import numpy as np

# Read the image
data = cv2.imread(r"C:\Users\HP\Desktop\career360\learning-python\WhatsApp Image 2024-07-01 at 11.08-Photoroom.jpg")

# Display the original image
#window_name = 'Original Image'
#cv2.imshow(window_name, data)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

A_Data=np.array(data)
print(A_Data)
A_Data.replace(255,34)
print(A_Data)
#A_Data.replace(

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


AttributeError: 'numpy.ndarray' object has no attribute 'replace'